=head1 Milton Keynes Perl Mongers Web Site Git Repository

=head2 About

This repository contains everything needed to build and maintain the
Web site for Milton Keynes Perl Mongers: L<< http://miltonkeynes.pm.org >>.

=head2 Subdirectories

=over

=item organisation

Organisational documents to help our group function

=item web

The document root for files to serve over HTTP

=back
