=head1 Organising Milton Keynes Perl Mongers Technical Meetings

=head2 Before the Event

=head3 Finding Speakers

=over

=item *

Ask people who have spoken before.

=item *

Flatter people in the pub at social meetings and tell them that you
want to hear them give a talk.

=item *

Ask on IRC (hang around for a few hours to let people reply) and the
mailing list.

=item *

Ask people who live nearby who have done interesting things with Perl,
such as members of other Mongers groups.

=item *

Put out a call for speakers anywhere appropriate, such as
L<< Lanyrd|http://lanyrd.com/topics/perl/calls/ >>.

=back

=head3 Finding a Venue

and projector

=head3 Announcing the Meeting

mailing list

web page

other sites (eg. lanyrd)

=head3 Helping People Attend

directions

car; public transport

lifts (usually from MK Central station)

phone number in case of help

=head2 On the Day

Time limits discussed with each speaker beforehand, five minute warnings

A conveniently placed break

Make sure people know where to go afterwards and have someone to take them there

=head2 After the Event

Add slides to Web site
